### ISSUE TITLE
Lack of  RADAM

### ISSUE THREAD

**Issue by YoloEliwa** [eunjin93/SICR_BCI#1]
Thank you very much for providing the source program, but there seems to be a missing "RADAM.py" file, can you add it?

**Comment by eunjin93** [comment]
Thanks for your attention to our work. 

You can utilize the official RADAM optimizer code at [https://github.com/LiyuanLucasLiu/RAdam](https://github.com/LiyuanLucasLiu/RAdam).

**Comment by YoloEliwa** [comment]
Thanks for your answer. 

And in the process of running the code，I have some questions. line 168 of the Run_EEGNet_1.py file, you reshape the **rele** and then put it into **global_disc**, but within **global_disc** is a conv2d, so that the dimensionality error occurs. 

We solved this problem by changing the variable name rele to rele_cpy on line 168. 

But I can't get your results in your paper. Accuracy rate fluctuates above and below 50%. Can you supply me with a correct copy of the source program and data files (.npy) , I have sent you an email with the same content. Thank you very much!
