### ISSUE TITLE
Some question about this code

### ISSUE THREAD

**Issue by YoloEliwa** [eunjin93/SICR_BCI#2]
In the process of running the code，I have some questions. line 168 of the **Run_EEGNet_1.py** file, you reshape the **rele** and then put it into **global_disc**, but within **global_disc** is a conv2d, so that the dimensionality error occurs.

We solved this problem by changing the variable name **rele** to **rele_cpy** on line 168.

But I can't get your results in your paper. Accuracy rate fluctuates above and below 50%. Can you supply me with a correct copy of the source program and data files？(.npy) 

I have sent you an email with the same content. Thank you very much! 

Hope to hear from you soon!

**Comment by YoloEliwa** [comment]
Have you solve this problem and get corresponding results? Thanks you so much.

**Comment by eunjin93** [comment]
Sorry for late reply. 
I just uploaded our updated code including "Preproecessing.py" file.
Unfortunately, we cannot distribute the dataset because we do not own it (and may go against the owner's rights). 
Could you try it once again with our pre-processing code?

**Comment by YoloEliwa** [comment]
Thank you very much for providing **Preprocessing.py**. And my problem has been solved!
